env:
  global:
    - CC_TEST_REPORTER_ID=1128aa02495bf10fead35135f55df7ba67a2884c72e65ece6603c5a4ed129f7e
language: go



before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./cc-test-reporter before-build
  - go test -coverprofile cover.out 
  - ./cc-test-reporter format-coverage --input-type gocov cover.out 
  - ./cc-test-reporter upload-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
